
export const ActiveProjectsUtils = [
    { title: "Photography Drone 1", completed: 10, },
    { title: "Photography Drone 2", completed: 40, },
    { title: "Photography Drone 3", completed: 80, },
    { title: "Photography Drone 4", completed: 60, },
    { title: "Photography Drone 5", completed: 11, },
    { title: "Photography Drone 6", completed: 19, },
    { title: "Photography Drone 7", completed: 70, },
    { title: "Photography Drone 8", completed: 100, },
    { title: "Photography Drone 9", completed: 100, },
    { title: "Photography Drone 10", completed: 10, },
    { title: "Photography Drone 11", completed: 10, },
    { title: "Photography Drone 12", completed: 10, },
    { title: "Photography Drone 13", completed: 10, },
    { title: "Photography Drone 14", completed: 10, },
    { title: "Photography Drone 15", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
    { title: "Photography Drone 16", completed: 10, },
]