export const RightSideBarUtils = [
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 1",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 2",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 3",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 4",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 5",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 6",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 6",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 6",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 6",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 6",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
    {
        picUrl: "https://i.pravatar.cc/150?u=a04258114e29026708c",
        name: "Name 6",
        designation: "Back end developer",
        company: "Brane",
        employeeId: "NH11234",
        team: "Autonomy engineer",
        email: "name@email.com",
    },
]